# Generated by Django 3.0.2 on 2020-01-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporter',
            name='phone_number',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='phone_number',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
